Repository iterative/cml, pull requests merged in 2021-09, with the labels that each got.

#700 Allow negative --idle-timeout on cml-runner
  bin/cml-runner.js
Labels: user experience

#707 npm & test time updates
  .github/workflows/test-deploy.yml
  package-lock.json
  package.json
Labels: dependencies, testing

#703 Unify commands and centralize logging
  .github/workflows/gitlab.yml
  Dockerfile
  bin/cml-pr.js
  bin/cml-pr.test.js
  bin/cml-publish.js
  bin/cml-publish.test.js
  bin/cml-send-comment.js
  bin/cml-send-comment.test.js
  bin/cml-send-github-check.js
  bin/cml-send-github-check.test.js
  bin/cml.js
  bin/cml.test.js
  bin/cml/pr.js
  bin/cml/pr.test.js
  bin/cml/publish.js
  bin/cml/publish.test.js
  bin/cml/runner.js
  bin/cml/runner.test.js
  bin/cml/send-comment.js
  bin/cml/send-comment.test.js
  bin/cml/send-github-check.js
  bin/cml/send-github-check.test.js
  bin/cml/tensorboard-dev.js
  bin/cml/tensorboard-dev.test.js
  bin/legacy.js
  bin/legacy.test.js
  package-lock.json
  package.json
  src/cml.js
  src/drivers/github.js
  src/pipe-args.js
Labels: enhancement, technical debt, user experience

#674 Proxy support
  README.md
  package-lock.json
  package.json
  src/cml.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.js
  src/drivers/gitlab.js
  src/utils.js
  src/utils.test.js
  tests/proxy.js
  tests/setup.js
  tests/teardown.js
Labels: enhancement

#716 docker: whitelist entrypoints
  Dockerfile
Labels: bug, cml-image

#717 readme: misc updates
  README.md
Labels: documentation, technical debt, cml-runner, cml-image

#726 Add missing backslash on container ENTRYPOINT
  Dockerfile
Labels: bug, p0-critical

#731 Fix runner status log reporting
  bin/cml/runner.js
Labels: bug, p0-critical

#733 add OS tests
  .github/workflows/test-deploy.yml
Labels: testing, deployment

#734 test dispatch & basic OS commands
  .github/workflows/test-deploy.yml
Labels: testing

#743 Include full stack traces on Winston JSONL logs
  bin/cml.js
Labels: bug, p0-critical

#737 Disable legacy command tests on Windows
  .github/workflows/test-deploy.yml
Labels: bug, testing

#732 Retry pipe EAGAIN on macOS
  src/pipe-args.js
Labels: bug, p0-critical

#739 Manage all the environment variables through yargs
  .github/workflows/test-deploy.yml
  Dockerfile
  bin/cml.js
  bin/cml/pr.js
  bin/cml/publish.js
  bin/cml/runner.js
  bin/cml/runner.test.js
  bin/cml/send-comment.js
  bin/cml/send-github-check.js
  bin/cml/tensorboard-dev.js
  package-lock.json
  package.json
  src/pipe-args.js
Labels: bug, p0-critical

#744 Use Winston whenever possible and log to stderr
  bin/cml.js
  bin/cml/runner.js
  src/drivers/github.js
Labels: technical debt, user experience

#725 Add ephemeral GitHub runner support
  src/drivers/github.js
Labels: technical debt, cml-runner

#720 Pin Vega and related dependencies on Dockerfile
  Dockerfile
Labels: bug, p0-critical

#712 Convert yargs builder functions to options objects and add per–command environment variables
  Dockerfile
  bin/cml.js
  bin/cml.test.js
  bin/cml/pr.js
  bin/cml/pr.test.js
  bin/cml/publish.js
  bin/cml/publish.test.js
  bin/cml/runner.js
  bin/cml/runner.test.js
  bin/cml/send-comment.js
  bin/cml/send-comment.test.js
  bin/cml/send-github-check.js
  bin/cml/send-github-check.test.js
  bin/cml/tensorboard-dev.js
  bin/cml/tensorboard-dev.test.js
  package-lock.json
  package.json
Labels: bug, enhancement, technical debt, p0-critical, user experience

#745 Update dependencies and fix merge mistake
  bin/cml/runner.js
  bin/cml/tensorboard-dev.test.js
  package-lock.json
  package.json
Labels: dependencies

#748 Cloud metadata
  bin/cml/runner.js
  bin/cml/runner.test.js
  src/terraform.js
  src/terraform.test.js
Labels: enhancement
