Repository iterative/cml, pull requests merged in 2021-11, with the labels that each got.

#809 send-comment rev-parse
  src/cml.js
  src/drivers/bitbucket_cloud.js
Labels: bug, p0-critical, cml-send-comment, cml-pr

#783 update to NodeJS==16
  .eslintrc.js
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/drivers/github.js
Labels: technical debt, dependencies

#811 0.9.0
  package-lock.json
  package.json
Labels: deployment

#812 manual docker release
  .github/workflows/test-deploy.yml
  package-lock.json
Labels: bug, deployment

#818 `cml runner` - Cleaner terraform JSON logs
  package-lock.json
  package.json
  src/utils.js
Labels: enhancement, cml-runner, user experience

#822 Bitbucket driver choice
  bin/cml/pr.js
  bin/cml/pr.test.js
  bin/cml/publish.js
  bin/cml/publish.test.js
  bin/cml/runner.test.js
Labels: technical debt, cml-publish, cml-runner, cml-pr
