Repository iterative/cml, pull requests merged in 2021-07, with the labels that each got.

#626 Require runners to be online when honoring --reuse
  bin/cml-runner.js
  src/cml.js
  src/cml.test.js
  src/drivers/github.js
  src/drivers/gitlab.js
Labels: cml-runner, enhancement

#624 Fix cml-pr reference handling for pull requests
  src/cml.js
  src/drivers/github.js
Labels: bug, cml-pr, p0-critical

#613 Skip Terraform version checks when not needed
  bin/cml-runner.js
Labels: bug, cml-runner

#604 test weekly (not daily)
  .github/workflows/test-deploy.yml
Labels: discussion, testing

#617 docs: rework README
  README.md
  src/cml.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
Labels: documentation, p1-important

#608 Fix endpoint detection logic, broken on FetchError
  src/drivers/gitlab.js
Labels: bug, gitlab, technical debt

#651 GL restarts the whole pipeline
  src/drivers/gitlab.js
Labels: bug, cml-runner

#643 Add GCP to cml-runner
  bin/cml-runner.js
Labels: cml-runner, enhancement

#642 Update containers' latest tag and add the docker.io/iterativeai registry
  .github/workflows/test-deploy.yml
Labels: deployment, enhancement

#667 Fix latest GPU container image tags
  .github/workflows/test-deploy.yml
  src/drivers/gitlab.js
Labels: bug, cml-image, cml-runner, p0-critical

#672 Add debug log to parseRunnerLog
  src/cml.js
Labels: enhancement, user experience

#668 misc YAML workflow tweaks
  .github/workflows/checkbot.yml
  .github/workflows/test-deploy.yml
  .gitlab-ci.yml
  README.md
Labels: cml-image, documentation, technical debt

#679 GH runner auto update
  bin/cml-runner.js
  src/cml.js
  src/drivers/github.js
Labels: bug, cml-image, enhancement, p0-critical
