Repository iterative/cml, pull requests merged in 2021-08, with the labels that each got.

#687 bump deps
  package-lock.json
  package.json
  src/cml.js
Labels: dependencies, technical debt

#684 readme: misc improvements
  README.md
Labels: documentation

#695 bump deps
  package-lock.json
  package.json
Labels: dependencies

#693 Jest global timeout and fixes
  bin/cml-pr.test.js
  bin/cml-publish.test.js
  bin/cml-send-comment.test.js
  bin/cml-send-github-check.test.js
  bin/cml-tensorboard-dev.js
  bin/cml-tensorboard-dev.test.js
  package-lock.json
  package.json
  src/cml.test.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.test.js
  src/drivers/gitlab.test.js
Labels: testing
