Repository iterative/cml, pull requests merged in 2021-06, with the labels that each got.

#572 Install python-dev in the docker
  Dockerfile
Labels: cml-image, dependencies

#574 Allow access to secrets for external contributors
  .github/workflows/test-deploy.yml
Labels: security, testing

#579 Install ping on Docker images
  Dockerfile
Labels: cml-image

#584 ssh_private is valid in TF
  bin/cml-runner.js
Labels: cml-runner, security

#585 Runners not unregistering due to camelCase
  src/drivers/github.js
Labels: cml-runner, p0-critical

#591 Hotfix Expose terraform aws_security_group param
  bin/cml-runner.js
  src/terraform.js
  src/terraform.test.js
Labels: cml-runner, p0-critical

#602 Allow newlines in SSH private keys
  bin/cml-runner.js
Labels: technical debt, user experience

#598 Allowlist non-sensitive data on Terraform state
  bin/cml-runner.js
Labels: bug, p0-critical, security

#601 Update maintainer in Dockerfile
  Dockerfile
Labels: technical debt

#581 Add `cml-send-comment --update`
  bin/cml-send-comment.js
  bin/cml-send-comment.test.js
  src/cml.js
  src/cml.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.js
  src/drivers/github.test.js
  src/drivers/gitlab.js
Labels: cml-send-comment, enhancement

#633 Update Bitbucket test commit hash
  .github/workflows/test-deploy.yml
Labels: bitbucket, bug, testing

#639 Remove debug triggers from gitlab.yml
  .github/workflows/gitlab.yml
Labels: technical debt, testing

#634 Fix inconsistencies between local and remote formatters
  .eslintrc.js
  .restyled.yaml
  package.json
Labels: technical debt, testing
