Repository iterative/cml, pull requests merged in 2021-12, with the labels that each got.

#844 fix local --global install
  .github/workflows/test-deploy.yml
Labels: bug, testing, flaky

#847 deploy: autorelease on tags
  .github/workflows/checkbot.yml
  .github/workflows/test-deploy.yml
Labels: technical debt, testing, deployment

#842 Standalone pkg
  .github/workflows/test-deploy.yml
  .gitignore
  package-lock.json
  package.json
  src/utils.js
Labels: technical debt, blocked, dependencies, deployment

#831 `cml runner` allow for a user set subnet
  bin/cml/runner.js
  bin/cml/runner.test.js
  src/terraform.js
  src/terraform.test.js
Labels: cml-runner, blocked, cloud-aws

#839 CML <-> TPI `task`
  bin/cml.test.js
  bin/cml/ci.js
  bin/cml/ci.test.js
  bin/cml/rerun-workflow.js
  bin/cml/rerun-workflow.test.js
  package-lock.json
  package.json
  src/cml.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.js
  src/drivers/github.test.js
  src/drivers/gitlab.js
  src/drivers/gitlab.test.js
Labels: enhancement, p1-important, cml-ci, cml-workflow

#849 0.10.0
  package-lock.json
  package.json
Labels: releases

#858 pin dvc==2.8.3
  Dockerfile
Labels: p0-critical, cml-image, dvc
