Repository iterative/cml, pull requests merged in 2021-05, with the labels that each got.

#493 Enforce strict argument parsing
  bin/cml-pr.js
  bin/cml-publish.js
  bin/cml-runner.js
  bin/cml-send-comment.js
  bin/cml-send-github-check.js
  bin/cml-tensorboard-dev.js
Labels: bug

#494 Refactor GitHub Actions release workflow and Dockerfile
  .github/workflows/publish.yml
  .github/workflows/release.yml
  Dockerfile
  docker/Dockerfile
  docker/Dockerfile-dev
  docker/Dockerfile-py3
Labels: cml-image, technical debt

#498 review all workflows
  .github/workflows/checkbot.yml
  .github/workflows/dependancron.yml
  .github/workflows/gitlab.yml
  .github/workflows/release.yml
Labels: technical debt

#500 Add support for GitHub Container Registry
  .github/workflows/release.yml
Labels: cml-image

#499 docs: image tags
  README.md
Labels: documentation

#492 docs: `repo_token` => `REPO_TOKEN`
  .github/workflows/checkbot.yml
  README.md
  bin/cml-pr.js
Labels: documentation

#504 Use actions/setup-node to configure the npm token
  .github/workflows/release.yml
Labels: bug

#505 Remove stray underscore in Docker Hub secrets
  .github/workflows/release.yml
Labels: bug

#511 fix GitLab GPU tests
  .gitlab-ci.yml
Labels: bug

#530 Create test-deploy.yml
  .dependancron
  .github/workflows/dependancron.yml
  .github/workflows/release.yml
  .github/workflows/test-deploy.yml
  Dockerfile
Labels: technical debt

#516 Fix pipe reading logic on Windows
  src/pipe-args.js
Labels: bug

#510 cml-pr command
  bin/cml-pr.js
  bin/cml-pr.test.js
  bin/cml-publish.js
  bin/cml-runner.js
  bin/cml-send-comment.js
  bin/cml-send-github-check.js
  package-lock.json
  package.json
  src/cml.js
  src/cml.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.js
  src/drivers/gitlab.js
Labels: enhancement

#539 Uncomment checkbot checks
  .github/workflows/checkbot.yml
Labels: bug

#543 Fixes fake cml repo for bitbucket publish
  src/cml.js
  src/drivers/bitbucket_cloud.js
Labels: cml-publish, p0-critical

#542 cml-pr prs list
  src/cml.js
Labels: p0-critical

#540 Rename --cloud-gpu tesla to v100
  bin/cml-runner.js
Labels: blocked, enhancement

#554 lint: fix camelCase
  bin/cml-pr.js
  bin/cml-publish.js
  bin/cml-runner.js
  bin/cml-send-comment.js
  bin/cml-send-github-check.js
  bin/cml-tensorboard-dev.js
  bin/cml-tensorboard-dev.test.js
  package-lock.json
  package.json
  src/cml.js
  src/cml.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.js
  src/drivers/github.test.js
  src/drivers/gitlab.js
  src/drivers/gitlab.test.js
  src/pipe-args.js
  src/terraform.js
  src/terraform.test.js
  src/utils.js
  src/utils.test.js
Labels: technical debt, testing

#564 Mask token in Terraform state output
  bin/cml-runner.js
Labels: p1-important, security

#555 imgs: (re)move & update
  README.md
  imgs/GitLab_CML_report.png
  imgs/action_in_progress.png
  imgs/bitbucket_cloud_pr.png
  imgs/cloud_case_snapshot.png
  imgs/cml_first_report.png
  imgs/dark_logo.png
  imgs/dvc_cml_long_report.png
  imgs/dvc_confusions.png
  imgs/dvc_diff.png
  imgs/dvc_metric.png
  imgs/fork_project.png
  imgs/github_cloud_case_lessshadow.png
  imgs/logo_v2.png
  imgs/make_pr.png
  imgs/title_strip.png
  imgs/title_strip_trim.png
  package.json
Labels: documentation, technical debt

#558 chat ops safety
  .github/workflows/checkbot.yml
Labels: security, technical debt, testing

#563 Unmask catch-all token exceptions
  src/cml.js
Labels: enhancement

#569 Improve GitLab API finder error handling
  src/drivers/gitlab.js
Labels: enhancement

#570 Release v0.4.4
  .github/workflows/checkbot.yml
  README.md
  bin/cml-pr.js
  bin/cml-publish.js
  bin/cml-runner.js
  bin/cml-send-comment.js
  bin/cml-send-github-check.js
  bin/cml-tensorboard-dev.js
  bin/cml-tensorboard-dev.test.js
  imgs/GitLab_CML_report.png
  imgs/action_in_progress.png
  imgs/bitbucket_cloud_pr.png
  imgs/cloud_case_snapshot.png
  imgs/cml_first_report.png
  imgs/dark_logo.png
  imgs/dvc_cml_long_report.png
  imgs/dvc_confusions.png
  imgs/dvc_diff.png
  imgs/dvc_metric.png
  imgs/fork_project.png
  imgs/github_cloud_case_lessshadow.png
  imgs/logo_v2.png
  imgs/make_pr.png
  imgs/title_strip.png
  imgs/title_strip_trim.png
  package-lock.json
  package.json
  src/cml.js
  src/cml.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
  src/drivers/github.js
  src/drivers/github.test.js
  src/drivers/gitlab.js
  src/drivers/gitlab.test.js
  src/pipe-args.js
  src/terraform.js
  src/terraform.test.js
  src/utils.js
  src/utils.test.js
Labels: bug, p1-important, security, technical debt, testing
