Repository iterative/cml, pull requests merged in 2022-01, with the labels that each got.

#864 Pin colors to 1.4.0
  package.json
Labels: bug, p0-critical

#870 docs: fix plot name
  README.md
Labels: bug, documentation

#872 Unpin DVC
  Dockerfile
Labels: technical debt, cml-image, dvc

#869 Rename --cloud-aws-subnet-id to --cloud-aws-subnet
  bin/cml/runner.js
  bin/cml/runner.test.js
  package-lock.json
  src/terraform.js
Labels: enhancement, user experience

#876 fix log encoding
  src/cml.js
Labels: technical debt

#878 Fix --idle-timeout on cml runner --cloud
  src/terraform.js
Labels: bug, p0-critical

#853 `github-send-check` usage warnings
  bin/cml/send-github-check.js
  bin/cml/send-github-check.test.js
  src/drivers/github.js
Labels: user experience, cml-send-github-check

#861 Runner docker volumes
  bin/cml/runner.js
  bin/cml/runner.test.js
  src/drivers/gitlab.js
  src/terraform.js
  src/terraform.test.js
Labels: cml-runner, ci-gitlab

#881 0.11.0
  package-lock.json
  package.json
Labels: bug, enhancement, releases

#882 Add human–readable duration syntax for runner --idle-timeout
  bin/cml/runner.js
  bin/cml/runner.test.js
  package-lock.json
  package.json
Labels: enhancement, user experience, p2-nice-to-have
