Repository iterative/cml, pull requests merged in 2022-09, with the labels that each got.

#1073 Introduce subcommands in a backwards-compatible way
  .gitignore
  bin/cml.js
  bin/cml/asset.js
  bin/cml/asset/publish.js
  bin/cml/asset/publish.test.js
  bin/cml/check.js
  bin/cml/check/create.js
  bin/cml/check/create.test.js
  bin/cml/ci.js
  bin/cml/ci.test.js
  bin/cml/comment.js
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  bin/cml/comment/update.js
  bin/cml/pr.js
  bin/cml/pr.test.js
  bin/cml/pr/create.js
  bin/cml/pr/create.test.js
  bin/cml/publish.js
  bin/cml/repo.js
  bin/cml/repo/prepare.js
  bin/cml/repo/prepare.test.js
  bin/cml/rerun-workflow.js
  bin/cml/rerun-workflow.test.js
  bin/cml/runner.js
  bin/cml/runner.test.js
  bin/cml/runner/launch.js
  bin/cml/runner/launch.test.js
  bin/cml/send-comment.js
  bin/cml/send-comment.test.js
  bin/cml/send-github-check.js
  bin/cml/tensorboard.js
  bin/cml/tensorboard/connect.js
  bin/cml/tensorboard/connect.test.js
  bin/cml/workflow.js
  bin/cml/workflow/rerun.js
  bin/cml/workflow/rerun.test.js
  bin/legacy/commands/ci.js
  bin/legacy/commands/publish.js
  bin/legacy/commands/rerun-workflow.js
  bin/legacy/commands/send-comment.js
  bin/legacy/commands/send-github-check.js
  bin/legacy/commands/tensorboard-dev.js
  bin/legacy/link.js
  bin/legacy/link.test.js
  package-lock.json
  package.json
  src/cml.js
Labels: enhancement, technical debt, ui/ux

#931 Simplify release process
  .github/workflows/release.yml
Labels: releases

#997 Separate workflows
  .github/workflows/checkbot.yml
  .github/workflows/images.yml
  .github/workflows/release.yml
  .github/workflows/test-deploy.yml
  README.md
Labels: testing, deployment, releases

#1166 Add support for `cml comment <verb> --publish-url`
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  src/cml.js
Labels: enhancement

#1165 workflow: dogfood & tidy
  .github/workflows/gitlab.yml
  .github/workflows/images.yml
  .github/workflows/release.yml
  .github/workflows/test-deploy.yml
  .github/workflows/trigger-external.yml
Labels: technical-debt, testing, releases

#1188 Fix release process, again
  .github/workflows/release.yml
  .github/workflows/test-deploy.yml
Labels: bug, releases

#1191 Fix opaque error messages when not `isatty`
  bin/cml.js
Labels: bug, ui/ux
