Repository iterative/cml, pull requests merged in 2022-02, with the labels that each got.

#900 Fix publish magic.mgc altered by babel
  .github/workflows/test-deploy.yml
  package.json
  src/utils.js
Labels: bug, p0-critical, cml-publish, binary

#901 Simplify magic.mgc loading code
  package-lock.json
  package.json
  src/utils.js
Labels: technical debt, cml-publish

#899 Move runner tests to AWS sandbox
  .github/workflows/checkbot.yml
  .gitlab-ci.yml
Labels: cml-runner, cloud-aws, testing, security, p2-nice-to-have, tpi
