Repository iterative/cml, pull requests merged in 2022-04, with the labels that each got.

#934 Remove autoMerge variable from prCreate
  src/cml.js
Labels: technical debt, cml-pr

#935 bump deps
  package-lock.json
  package.json
Labels: technical debt, dependencies, security

#936 0.13.0
  package-lock.json
  package.json
Labels: releases

#943 Add support for Bitbucket native uploads
  .eslintrc.js
  src/drivers/bitbucket_cloud.js
  src/drivers/bitbucket_cloud.test.js
Labels: enhancement, ci-bitbucket, p2-nice-to-have

#945 ci: expose --user-email --user-name
  bin/cml/ci.js
  bin/cml/ci.test.js
Labels: enhancement, cml-ci

#949 0.14.0
  package-lock.json
  package.json
Labels: releases

#950 Fix GitHub `actions.listWorkflowRunsForRepo` status filtering
  src/drivers/github.js
Labels: bug, p0-critical, cml-runner

#948 Paginate octokit requests
  src/drivers/github.js
Labels: bug, p0-critical, cml-runner, ci-github

#957 ci: add `--unshallow`
  bin/cml/ci.js
  bin/cml/ci.test.js
  src/cml.js
Labels: enhancement, cml-ci

#959 Fix pull request auto-merge edge cases
  src/drivers/github.js
Labels: bug, p1-important, cml-pr, ci-github

#962 `bitbucket` Driver: body can be undefined
  src/drivers/bitbucket_cloud.js
Labels: bug, p1-important, ci-bitbucket

#963 Update `node` engine version constraint
  package.json
Labels: releases

#954 Build `pkg` standalone binaries for more platforms
  .github/workflows/test-deploy.yml
  package.json
Labels: enhancement, p1-important, binary

#966 Revert conditional chaining
  src/drivers/bitbucket_cloud.js
Labels: technical debt

#958 0.15.0
  package-lock.json
  package.json
Labels: releases

#885 specify TPI version
  bin/cml/runner.js
  bin/cml/runner.test.js
  src/terraform.js
  src/terraform.test.js
Labels: bug, cml-runner, releases, tpi

#967 Hide `cml runner --tpi-version`
  bin/cml/runner.js
  bin/cml/runner.test.js
Labels: cml-runner

#980 Revert client–side GitHub Actions job filtering
  src/drivers/github.js
Labels: bug, technical debt, p0-critical, cml-runner, ci-github

#981 0.15.1
  package-lock.json
  package.json
Labels: releases

#976 Document Bitbucket `cml publish --native`
  bin/cml/publish.js
  bin/cml/publish.test.js
  src/cml.js
  src/cml.test.js
Labels: documentation, cml-publish, ci-bitbucket

#974 Add CWD to Git's `safe.directory` with `cml ci`
  src/cml.js
Labels: bug, p0-critical

#985 0.15.2
  package-lock.json
  package.json
Labels: releases

#986 Refine #974 safe directory code
  src/cml.js
Labels: technical debt
