Repository iterative/cml, pull requests merged in 2022-10, with the labels that each got.

#1199 Exclude internal projects & tests from analytics
  src/analytics.js
Labels: testing

#1206 npm audit fix
  package-lock.json
Labels: dependencies

#1208 Enable `cml comment create --publish` by default
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
Labels: enhancement, cml-comment, ui/ux

#1218 CodeQL recommendations
  bin/cml/asset/publish.js
  src/cml.js
  src/drivers/github.js
Labels: technical-debt, p2-nice-to-have

#1096 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: blocked, awaiting-response

#1209 fix driver detection
  bin/cml/runner/launch.js
Labels: bug, technical-debt, p0-critical

#1220 Downgrade v18.0.4 to v0.18.4
  package-lock.json
  package.json
Labels: bug, releases

#1172 Enhance telemetry data and exclude `tensorboard` tracebacks
  Dockerfile
  bin/cml.js
  bin/cml/asset/publish.js
  bin/cml/check/create.js
  bin/cml/comment/create.js
  bin/cml/pr.js
  bin/cml/pr/create.js
  bin/cml/repo/prepare.js
  bin/cml/runner.js
  bin/cml/runner/launch.js
  bin/cml/tensorboard/connect.e2e.test.js
  bin/cml/tensorboard/connect.js
  bin/cml/workflow/rerun.js
  package-lock.json
  package.json
  src/analytics.e2e.test.js
  src/analytics.js
Labels: technical-debt, telemetry

#1217 Install `ldid` with `brew`
  .github/workflows/test-deploy.yml
Labels: security, releases

#1227 Add deprecation notices to legacy commands
  bin/legacy/commands/ci.js
  bin/legacy/commands/publish.js
  bin/legacy/commands/rerun-workflow.js
  bin/legacy/commands/send-comment.js
  bin/legacy/commands/send-github-check.js
  bin/legacy/commands/tensorboard-dev.js
  bin/legacy/deprecation.js
  src/drivers/github.js
Labels: ui/ux

#1202 Allow creation of issue comments in cml
  .github/workflows/test-deploy.yml
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  src/cml.js
  src/drivers/bitbucket_cloud.e2e.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.e2e.test.js
  src/drivers/github.js
  src/drivers/gitlab.e2e.test.js
  src/drivers/gitlab.js
Labels: enhancement, cml-comment

#1210 CLI consistency: --native => --publish-native
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
Labels: ui/ux

#1230 Assume branch protection disabled if not available
  src/drivers/github.js
Labels: bug, cml-pr

#1225 Use the standalone command-line tool to destroy runners
  bin/cml/runner/launch.js
Labels: cml-runner, cloud-common

#1232 Provide Docs URLs in `--help` messaging
  bin/cml.test.js
  bin/cml/asset/publish.js
  bin/cml/check/create.js
  bin/cml/comment/create.js
  bin/cml/comment/update.js
  bin/cml/pr/create.e2e.test.js
  bin/cml/pr/create.js
  bin/cml/repo/prepare.js
  bin/cml/runner/launch.js
  bin/cml/runner/launch.test.js
  bin/cml/tensorboard/connect.js
  bin/cml/workflow/rerun.js
  package-lock.json
Labels: ui/ux

#1236 Exclude `error` from successful analytics payloads
  src/analytics.js
Labels: bug

#1238 Configure winston logging when running terraform tests
  src/terraform.test.js
Labels: technical-debt, testing, p2-nice-to-have

#1235 Hide `--rm-watermark` option when invoking CML CLI
  bin/cml/asset/publish.js
  bin/cml/asset/publish.test.js
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  bin/cml/tensorboard/connect.js
  bin/cml/tensorboard/connect.test.js
Labels: hacktoberfest, cml-comment, p2-nice-to-have, external-request

#1233 Add `ci --fetch-depth`, deprecate `ci --unshallow`
  bin/cml/repo/prepare.js
  bin/cml/repo/prepare.test.js
  src/cml.js
Labels: enhancement, hacktoberfest, cml-ci, external-request

#1242 Add cloud instance & accelerator types telemetry
  bin/cml/runner/launch.js
Labels: cml-runner, telemetry, cloud-common

#1173 Augment watermark with label
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  src/cml.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.js
  src/drivers/gitlab.js
  src/utils.js
Labels: enhancement, technical-debt, cml-comment, ui/ux
