Repository iterative/cml, pull requests merged in 2022-11, with the labels that each got.

#1247 Fix environment variable aliases
  bin/cml.js
Labels: bug

#1240 misc README updates
  README.md
Labels: documentation

#1249 Update example repository links
  README.md
Labels: documentation

#1257 Add a .nvmrc file to support using the intended Node.js version
  .nvmrc
Labels: technical-debt

#1259 replace set-output => GITHUB_OUTPUT
  .github/workflows/gitlab.yml
  .github/workflows/images.yml
Labels: technical-debt
