Repository iterative/cml, pull requests merged in 2022-12, with the labels that each got.

#1265 Default cml name change paired with (tpi#726)
  bin/cml/runner/launch.js
Labels: external-request

#1267 Release action: fix multi-line `output`
  .github/workflows/images.yml
Labels: releases

#1263 Allow running `cml pr create` without files
  bin/cml/pr.js
  bin/cml/pr/create.e2e.test.js
  bin/cml/pr/create.js
  src/cml.js
Labels: enhancement

#1275 Harden ancillary `exec` function
  bin/cml.test.js
  bin/cml/asset/publish.e2e.test.js
  bin/cml/asset/publish.test.js
  bin/cml/check/create.e2e.test.js
  bin/cml/check/create.test.js
  bin/cml/comment/create.e2e.test.js
  bin/cml/comment/create.test.js
  bin/cml/pr/create.e2e.test.js
  bin/cml/repo/prepare.test.js
  bin/cml/runner/launch.e2e.test.js
  bin/cml/runner/launch.js
  bin/cml/runner/launch.test.js
  bin/cml/tensorboard/connect.e2e.test.js
  bin/cml/tensorboard/connect.js
  bin/cml/tensorboard/connect.test.js
  bin/cml/workflow/rerun.test.js
  bin/legacy/link.e2e.test.js
  src/analytics.js
  src/cml.js
  src/drivers/bitbucket_cloud.e2e.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.e2e.test.js
  src/drivers/github.js
  src/drivers/gitlab.e2e.test.js
  src/drivers/gitlab.js
  src/terraform.js
  src/utils.js
  src/utils.test.js
Labels: bug, p0-critical, security

#1281 #1275 follow-up
  src/cml.js
Labels: bug, p0-critical

#1284 Add some debug logging for bitbucket and gitlab driver requests.
  src/drivers/bitbucket_cloud.js
  src/drivers/gitlab.js
Labels: testing

#1288 fix invalid deprecation warnings
  bin/cml/repo/prepare.test.js
  bin/legacy/commands/ci.js
  bin/legacy/commands/publish.js
Labels: p0-critical, cml-publish, cml-comment, ui/ux, cml-ci, external-request

#1269 `cml ci` fetch tags with depth/unshallow
  src/cml.js
Labels: cml-ci

#1228 Feature comment target
  .github/workflows/test-deploy.yml
  README.md
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  src/cml.js
  src/commenttarget.js
  src/commenttarget.test.js
  src/drivers/bitbucket_cloud.e2e.test.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.e2e.test.js
  src/drivers/github.js
  src/drivers/gitlab.e2e.test.js
  src/drivers/gitlab.js
Labels: enhancement, cml-comment, ui/ux

#1277 Allow argument-less cml pr (Revert of the Revert)
  .github/workflows/release.yml
  bin/cml/pr.js
  bin/cml/pr/create.e2e.test.js
  bin/cml/pr/create.js
  bin/cml/repo/prepare.test.js
  bin/legacy/commands/ci.js
  src/cml.js
  src/drivers/github.js
Labels: p0-critical, external-request

#1293 invalid tf usage
  src/terraform.js
Labels: bug, p0-critical

#1294 Linters - leave yaml's alone
  .restyled.yaml
  package.json
Labels: p2-nice-to-have

#1272 Rename `--token` to `--driver-token`
  bin/cml.js
  bin/cml.test.js
  bin/cml/asset/publish.js
  bin/cml/asset/publish.test.js
  bin/cml/check/create.js
  bin/cml/check/create.test.js
  bin/cml/comment/create.js
  bin/cml/comment/create.test.js
  bin/cml/pr.js
  bin/cml/pr/create.e2e.test.js
  bin/cml/pr/create.js
  bin/cml/repo/prepare.js
  bin/cml/repo/prepare.test.js
  bin/cml/runner.js
  bin/cml/runner/launch.js
  bin/cml/runner/launch.test.js
  bin/cml/tensorboard/connect.js
  bin/cml/tensorboard/connect.test.js
  bin/cml/workflow/rerun.js
  bin/cml/workflow/rerun.test.js
Labels: enhancement, ui/ux

#1300 Add missing `await` and increase polling delay
  src/drivers/github.js
Labels: bug, cml-runner

#1299 Patch `cml runner` idleness detection logic
  bin/cml/runner/launch.js
Labels: bug
