Repository iterative/cml, pull requests merged in 2023-01, with the labels that each got.

#1309 Add the sha of the the current commit to the watermark as the fragment of the watermark image url.
  src/cml.js
  src/watermark.js
  src/watermark.test.js
Labels: bug, cml-comment

#1302 Implement `cml runner launch --cloud-image`
  bin/cml/runner/launch.js
  src/terraform.js
Labels: enhancement, cml-runner

#1314 hotfix hidden options
  bin/cml/runner/launch.js
Labels: bug, p0-critical, cml-runner, cloud-gcp, cloud-common

#1317 Fix `yargs` global options bypassing strict checks
  bin/cml.js
  bin/cml/asset/publish.js
  bin/cml/check/create.js
  bin/cml/comment/create.js
  bin/cml/pr.js
  bin/cml/pr/create.js
  bin/cml/repo/prepare.js
  bin/cml/runner.js
  bin/cml/runner/launch.js
  bin/cml/tensorboard/connect.js
  bin/cml/workflow/rerun.js
Labels: bug, p0-critical, ui/ux

#1321 Add missing ProxyAgent to node-fetch
  src/utils.js
Labels: bug, p0-critical

#1305 Display a meaningful message if `git` is not available
  src/cml.js
Labels: enhancement, ui/ux

#1323 Send external dispatch on push to master
  .github/workflows/trigger-external.yml
Labels: testing
