Repository iterative/cml, pull requests merged in 2024-05, with the labels that each got.

#1448 Quote `$GITHUB_HEAD_REF` on `release.yml`
  .github/workflows/release.yml
Labels: security

#802 Add exclusion list for environment variables
  src/cml.js
  src/drivers/bitbucket_cloud.js
  src/drivers/github.js
  src/drivers/gitlab.js
Labels: p1-important, cml-runner, security, discussion

#1447 Fix flawed `unist-util-visit` usage
  src/cml.js
Labels: bug

#1465 Pin @npcz/magic to 1.3.12
  package-lock.json
  package.json
Labels: bug
